spring:
  application:
    name: notification-service
  mail:
    host: localhost
    port: 25
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: notification-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://jaeger:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
